tasks:
  - init: yarn && clear
github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
vscode:
  extensions:
    - sdras.night-owl
    - vscode-icons-team.vscode-icons
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - juanblanco.solidity

