tasks:
  - name: App
    init: yarn
    command: yarn start
  - name: Chain
    command: yarn chain
    openMode: split-right
  - name: Deployment
    command: yarn deploy
    openMode: split-right
github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
vscode:
  extensions:
    - sdras.night-owl
    - vscode-icons-team.vscode-icons
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - juanblanco.solidity

