tasks:
  - name: App
    init: >
      yarn &&
      gp sync-done install
    command: yarn start
  - name: Chain
    init: >
      gp sync-await install &&
      yarn chain &&
      gp sync-done chain
    openMode: split-right
  - name: Deployment
    init: gp sync-await chain
    command: yarn deploy
    openMode: split-right
ports:
  - port: 3000
    onOpen: open-browser
  - port: 8545
    onOpen: ignore
github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
vscode:
  extensions:
    - sdras.night-owl
    - vscode-icons-team.vscode-icons
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - juanblanco.solidity